[versions]
ldlib = "1.0.40.b"
registrate = "MC1.20-1.3.11"
configuration = "2.2.0"
mixinExtras = "0.5.0-rc.3"
gtceu = "7.4.0"
jei = "15.20.0.115"
gtnn = "1.3.5"
gtca = "2.1.0-beta"
gtmu = "2.4.0"
gtmthings = "6843500"
botania = "1.20.1-450-forge"
curios = "5.14.1+1.20.1"
patchouli = "1.20.1-84.1-forge"
adastra = "1.15.20"
botarium = "2.3.4"
resconfig = "DERs8u7v"
reslib = "OhsHaCcW"
deafission = "1.20.1-0.14.0"
ae2 = "15.4.10"
guideme = "20.1.14"

[libraries]
ldlib               = { module = "com.lowdragmc.ldlib:ldlib-forge-1.20.1", version.ref = "ldlib" }
registrate          = { module = "com.tterrag.registrate:Registrate", version.ref = "registrate" }
configuration       = { module = "dev.toma.configuration:configuration-forge-1.20.1", version.ref = "configuration" }
mixinExtras-common  = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinExtras" }
mixinExtras-forge   = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixinExtras" }
gtceu               = { module = "com.gregtechceu.gtceu:gtceu-1.20.1", version.ref = "gtceu"}
jei                 = { module = "mezz.jei:jei-1.20.1-forge", version.ref = "jei"}
gtnn                = { module = "maven.modrinth:gtnn", version.ref = "gtnn"}
gtca                = { module = "maven.modrinth:gt-community-additions", version.ref = "gtca"}
botania             = { module = "maven.modrinth:botania", version.ref = "botania"}
curios              = { module = "maven.modrinth:curios", version.ref = "curios"}
patchouli           = { module = "maven.modrinth:patchouli", version.ref = "patchouli"}
adastra             = { module = "maven.modrinth:ad-astra", version.ref = "adastra"}
botarium            = { module = "maven.modrinth:botarium", version.ref = "botarium"}
resconfig           = { module = "maven.modrinth:resourceful-config", version.ref = "resconfig"}
reslib              = { module = "maven.modrinth:resourceful-lib", version.ref = "reslib"}
gtmu                = { module = "maven.modrinth:gregtech-modern-utilities", version.ref = "gtmu"}
gtmthings           = { module = "curse.maven:gtmthings-1104310", version.ref = "gtmthings"}
deafission          = { module = "maven.modrinth:deafission", version.ref = "deafission"}
ae2                 = { module = "maven.modrinth:ae2", version.ref = "ae2" }
guideme             = { module = "maven.modrinth:guideme", version.ref = "guideme"}