[versions]
ldlib = "1.0.40.b"
registrate = "MC1.20-1.3.11"
configuration = "2.2.0"
mixinExtras = "0.5.0-rc.3"
gtceu = "7.1.4"
jei = "15.20.0.112"


[libraries]
ldlib               = { module = "com.lowdragmc.ldlib:ldlib-forge-1.20.1", version.ref = "ldlib" }
registrate          = { module = "com.tterrag.registrate:Registrate", version.ref = "registrate" }
configuration       = { module = "dev.toma.configuration:configuration-forge-1.20.1", version.ref = "configuration" }
mixinExtras-common  = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinExtras" }
mixinExtras-forge   = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixinExtras" }
gtceu               = { module = "com.gregtechceu.gtceu:gtceu-1.20.1", version.ref = "gtceu"}
jei                 = { module = "mezz.jei:jei-1.20.1-forge", version.ref = "jei"}
